export const AUTH = {
  FIELD_INITIALIZATION: 'FIELD_INITIALIZATION',
  CALL_LOGIN_API: {
    MAIN: 'CALL_LOGIN_API',
    SUCCESS: 'CALL_LOGIN_API_SUCCESS',
    FAILURE: 'CALL_LOGIN_API_FAILURE'
  },
  UPDATE_USERNAME: {
    MAIN: 'PROFILE_UPDATE',
    SUCCESS: 'PROFILE_UPDATE_SUCCESS',
    FAILURE: 'PROFILE_UPDATE_FAILURE'
  },
  ROUTE_PREPARED: {
    MAIN: 'ROUTE_PREPARED',
    SUCCESS: 'ROUTE_PREPARED_SUCCESS',
    FAILURE: 'ROUTE_PREPARED_FAILURE'
  },
  GET_PERMISSIONS: {
    MAIN: 'GET_PERMISSIONS',
    SUCCESS: 'GET_PERMISSIONS_SUCCESS',
    FAILURE: 'GET_PERMISSIONS_FAILURE'
  },
  CLEAR_LOGIN_DATA: {
    MAIN: 'CLEAR_LOGIN_DATA',
    SUCCESS: 'CLEAR_LOGIN_DATA_SUCCESS',
    FAILURE: 'CLEAR_LOGIN_DATA_FAILURE'
  }
 
};
