export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const COMMON = {
  FIELD_INITIALIZER: 'FIELD_INITIALIZER',
  TEST_CONST: {
    MAIN: 'TEST_CONST',
    SUCCESS: 'TEST_CONST_SUCCESS',
    FAILURE: 'TEST_CONST_FAILURE'
  },
  SET_LANGUAGE: {
    MAIN: 'SET_LANGUAGE',
    SUCCESS: 'SET_LANGUAGE_SUCCESS',
    FAILURE: 'SET_LANGUAGE_FAILURE'
  },
  SET_MENU: {
    MAIN: 'SET_MENU',
    SUCCESS: 'SET_MENU_SUCCESS',
    FAILURE: 'SET_MENU_FAILURE'
  },
  SYSTEM_SETTINGS_MENU: {
    MAIN: 'SYSTEM_SETTINGS_MENU',
    SUCCESS: 'SYSTEM_SETTINGS_MENU_SUCCESS',
    FAILURE: 'SYSTEM_SETTINGS_MENU_FAILURE'
  },
  MAIL_MAGAZINE_MENU: {
    MAIN: 'MAIL_MAGAZINE_MENU',
    SUCCESS: 'MAIL_MAGAZINE_MENU_SUCCESS',
    FAILURE: 'MAIL_MAGAZINE_MENU_FAILURE'
  },
  STATISTICS_MENU: {
    MAIN: 'STATISTICS_MENU',
    SUCCESS: 'STATISTICS_MENU_SUCCESS',
    FAILURE: 'STATISTICS_MENU_FAILURE'
  },
  GLOBAL_SEARCH_TEXT: {
    MAIN: 'GLOBAL_SEARCH_TEXT',
    SUCCESS: 'GLOBAL_SEARCH_TEXT_SUCCESS',
    FAILURE: 'GLOBAL_SEARCH_TEXT_FAILURE'
  },
  ARTICLE_PREVIEW: {
    MAIN: 'ARTICLE_PREVIEW',
    SUCCESS: 'ARTICLE_PREVIEW_SUCCESS',
    FAILURE: 'ARTICLE_PREVIEW_FAILURE'
  }
};
